on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          service_name: travis-pro
          github-token: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          pip install 
          coverage run -m pytest swagger2locustio/tests/